### ISSUE TITLE
Make spectral standard view

### ISSUE THREAD

**Issue by kelle** [SIMPLE-AstroDB/SIMPLE-web#26]
It would be great to have a "shortcut" to access spectral standards. We could just start with a custom query but eventually figure out how to provide bulk downloads of data for the sets of standards.

**Comment by Will-Cooper** [comment]
I'm tempted to close this issue and #24 as I'm not convinced we want to overplot spectral standards as that opens up a whole new ballpark (e.g. which standards do we use at what wavelengths and separated by what spectral type)? A user can already (since #55) view a normalised spectrum and download it; making any clever online tools does really increase the site complexity. Thoughts?
